# Generated by Django 6.0.6 on 2026-06-09 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('event_type', models.CharField(choices=[('conference', 'Conference'), ('service', 'Service'), ('workshop', 'Workshop'), ('prayer_meeting', 'Prayer Meeting'), ('concert', 'Concert'), ('seminar', 'Seminar'), ('social', 'Social Event'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('upcoming', 'Upcoming'), ('live', 'Live'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='upcoming', max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('expected_attendance', models.IntegerField(blank=True, null=True)),
                ('speaker_names', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, upload_to='events/')),
                ('banner', models.ImageField(blank=True, upload_to='event_banners/')),
                ('agenda', models.JSONField(blank=True, default=list)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('registration_url', models.URLField(blank=True)),
                ('is_free', models.BooleanField(default=True)),
                ('ticket_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('current_attendees', models.IntegerField(default=0)),
                ('requires_registration', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='EventAttendee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_status', models.CharField(choices=[('registered', 'Registered'), ('checked_in', 'Checked In'), ('no_show', 'No Show'), ('cancelled', 'Cancelled')], default='registered', max_length=20)),
                ('registration_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_time', models.DateTimeField(blank=True, null=True)),
                ('ticket_code', models.CharField(blank=True, max_length=100, unique=True)),
                ('number_of_guests', models.IntegerField(default=1)),
                ('special_requirements', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['event', 'registration_time'],
            },
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('event_starting', 'Event Starting'), ('event_update', 'Event Update'), ('event_cancelled', 'Event Cancelled'), ('reminder', 'Reminder'), ('alert', 'Alert')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sent_to_all', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
    ]
