# Generated by Codex on 2026-06-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='locations.location'),
        ),
        migrations.AddField(
            model_name='event',
            name='manual_location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
