# Generated by Django 6.0.6 on 2026-06-09 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('congestion', 'Congestion'), ('bottleneck', 'Bottleneck'), ('unusual_activity', 'Unusual Activity'), ('infrastructure_issue', 'Infrastructure Issue'), ('safety_concern', 'Safety Concern'), ('weather_impact', 'Weather Impact')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('monitoring', 'Monitoring'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('radius_meters', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdBehaviorMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('peak_occupancy_time', models.TimeField()),
                ('peak_occupancy_percentage', models.FloatField()),
                ('average_occupancy_percentage', models.FloatField()),
                ('total_visitors_count', models.IntegerField()),
                ('average_dwell_time_minutes', models.IntegerField()),
                ('flow_efficiency_score', models.FloatField()),
                ('incident_count', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CrowdDensity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('density_level', models.CharField(choices=[('empty', 'Empty'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very High'), ('critical', 'Critical')], max_length=20)),
                ('estimated_people_count', models.IntegerField()),
                ('percentage_capacity', models.FloatField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='CrowdFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('north', 'North'), ('south', 'South'), ('east', 'East'), ('west', 'West'), ('northeast', 'Northeast'), ('northwest', 'Northwest'), ('southeast', 'Southeast'), ('southwest', 'Southwest')], max_length=20)),
                ('speed', models.CharField(choices=[('stationary', 'Stationary'), ('slow', 'Slow'), ('normal', 'Normal'), ('fast', 'Fast')], max_length=20)),
                ('estimated_flow_rate', models.IntegerField()),
                ('congestion_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('incident_reported', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictedCongestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('predicted_time', models.DateTimeField()),
                ('predicted_crowd_percentage', models.FloatField()),
                ('confidence_level', models.FloatField()),
                ('recommendation', models.TextField(blank=True)),
                ('prediction_made_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['predicted_time'],
            },
        ),
    ]
