# Generated by Django 6.0.6 on 2026-06-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crowd_intelligence', '0001_initial'),
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdalert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_crowd_alerts', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='crowdalert',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_alerts', to='locations.location'),
        ),
        migrations.AddField(
            model_name='crowdbehaviormetric',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_metrics', to='locations.location'),
        ),
        migrations.AddField(
            model_name='crowddensity',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_densities', to='locations.location'),
        ),
        migrations.AddField(
            model_name='crowdflow',
            name='end_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_flow_to', to='locations.location'),
        ),
        migrations.AddField(
            model_name='crowdflow',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crowd_flow_from', to='locations.location'),
        ),
        migrations.AddField(
            model_name='predictedcongestion',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicted_congestion', to='locations.location'),
        ),
        migrations.AddIndex(
            model_name='crowdalert',
            index=models.Index(fields=['status', 'severity'], name='crowd_intel_status_71d5a1_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdalert',
            index=models.Index(fields=['created_at'], name='crowd_intel_created_ba7125_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='crowdbehaviormetric',
            unique_together={('location', 'date')},
        ),
        migrations.AddIndex(
            model_name='crowddensity',
            index=models.Index(fields=['location', 'recorded_at'], name='crowd_intel_locatio_69e045_idx'),
        ),
        migrations.AddIndex(
            model_name='crowddensity',
            index=models.Index(fields=['density_level'], name='crowd_intel_density_f85ea3_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdflow',
            index=models.Index(fields=['start_location', 'end_location'], name='crowd_intel_start_l_93ab31_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdflow',
            index=models.Index(fields=['recorded_at'], name='crowd_intel_recorde_59f186_idx'),
        ),
        migrations.AddIndex(
            model_name='predictedcongestion',
            index=models.Index(fields=['location', 'predicted_time'], name='crowd_intel_locatio_27511d_idx'),
        ),
    ]
