# Generated by Django 6.0.6 on 2026-06-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0002_initial'),
        ('navigation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='navigation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigations', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='navigationcheckpoint',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.location'),
        ),
        migrations.AddField(
            model_name='navigationcheckpoint',
            name='navigation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkpoints', to='navigation.navigation'),
        ),
        migrations.AddField(
            model_name='route',
            name='end_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='locations.location'),
        ),
        migrations.AddField(
            model_name='route',
            name='start_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='locations.location'),
        ),
        migrations.AddField(
            model_name='navigation',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='navigation.route'),
        ),
        migrations.AddField(
            model_name='landmark',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landmarks', to='navigation.route'),
        ),
        migrations.AlterUniqueTogether(
            name='navigationcheckpoint',
            unique_together={('navigation', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['start_location', 'end_location'], name='navigation__start_l_99e1f1_idx'),
        ),
        migrations.AddIndex(
            model_name='route',
            index=models.Index(fields=['route_type'], name='navigation__route_t_68cf91_idx'),
        ),
        migrations.AddIndex(
            model_name='navigation',
            index=models.Index(fields=['user', 'status'], name='navigation__user_id_63e5b4_idx'),
        ),
        migrations.AddIndex(
            model_name='navigation',
            index=models.Index(fields=['started_at'], name='navigation__started_cf9252_idx'),
        ),
    ]
