# Generated by Django 6.0.6 on 2026-06-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationreview',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_reviews', to='users.customuser'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['location_type'], name='locations_l_locatio_aa6df5_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['status'], name='locations_l_status_2adbb3_idx'),
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['latitude', 'longitude'], name='locations_l_latitud_739c67_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='locationhours',
            unique_together={('location', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='locationreview',
            unique_together={('location', 'user')},
        ),
    ]
