# Generated by Django 6.0.6 on 2026-06-09 08:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emergency_type', models.CharField(choices=[('medical', 'Medical Emergency'), ('security', 'Security Incident'), ('fire', 'Fire/Smoke'), ('accident', 'Accident'), ('missing_person', 'Missing Person'), ('hazard', 'Environmental Hazard'), ('crowd_crush', 'Crowd Crush Risk'), ('other', 'Other')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('confirmed', 'Confirmed'), ('response_sent', 'Response Sent'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('false_alarm', 'False Alarm')], default='reported', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField()),
                ('people_affected_count', models.IntegerField(blank=True, null=True)),
                ('injuries_reported', models.BooleanField(default=False)),
                ('medical_attention_needed', models.BooleanField(default=False)),
                ('additional_notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='emergency_reports/')),
                ('video_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('dispatched', 'Dispatched'), ('en_route', 'En Route'), ('on_scene', 'On Scene'), ('assisting', 'Assisting'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='dispatched', max_length=20)),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('departure_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('actions_taken', models.JSONField(blank=True, default=list)),
                ('vehicles_dispatched', models.JSONField(blank=True, default=list)),
                ('personnel_assigned', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('medical', 'Medical'), ('security', 'Security'), ('fire', 'Fire'), ('police', 'Police'), ('rescue', 'Rescue'), ('counseling', 'Counseling'), ('chaplain', 'Chaplain Services')], max_length=50)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('description', models.TextField()),
                ('available_24_7', models.BooleanField(default=False)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('staff_count', models.IntegerField(blank=True, null=True)),
                ('equipment_list', models.JSONField(blank=True, default=list)),
                ('response_time_minutes', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('total_incidents', models.IntegerField(default=0)),
                ('medical_incidents', models.IntegerField(default=0)),
                ('security_incidents', models.IntegerField(default=0)),
                ('other_incidents', models.IntegerField(default=0)),
                ('average_response_time_minutes', models.FloatField(blank=True, null=True)),
                ('critical_incidents', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SafetyTip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('crowd_safety', 'Crowd Safety'), ('health', 'Health'), ('security', 'Security'), ('accessibility', 'Accessibility'), ('weather', 'Weather'), ('first_aid', 'First Aid'), ('emergency_procedures', 'Emergency Procedures')], max_length=50)),
                ('content', models.TextField()),
                ('icon', models.ImageField(blank=True, upload_to='safety_tips/')),
                ('priority', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
