# Generated by Django 6.0.6 on 2026-06-09 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emergency_services', '0002_initial'),
        ('locations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reports', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='emergency_report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='emergency_services.emergencyreport'),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_responses', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='emergencyservice',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_services', to='locations.location'),
        ),
        migrations.AddField(
            model_name='emergencyresponse',
            name='emergency_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='emergency_services.emergencyservice'),
        ),
        migrations.AddField(
            model_name='incidenthistory',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incident_history', to='locations.location'),
        ),
        migrations.AddIndex(
            model_name='emergencyreport',
            index=models.Index(fields=['status', 'severity'], name='emergency_s_status_27a691_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyreport',
            index=models.Index(fields=['emergency_type'], name='emergency_s_emergen_178cae_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyreport',
            index=models.Index(fields=['created_at'], name='emergency_s_created_2b589f_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyservice',
            index=models.Index(fields=['service_type'], name='emergency_s_service_98af7a_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyservice',
            index=models.Index(fields=['location'], name='emergency_s_locatio_e40d9a_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyresponse',
            index=models.Index(fields=['status'], name='emergency_s_status_bebd26_idx'),
        ),
        migrations.AddIndex(
            model_name='emergencyresponse',
            index=models.Index(fields=['created_at'], name='emergency_s_created_4a3aa5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='incidenthistory',
            unique_together={('location', 'date')},
        ),
    ]
